
version: 2.1

parameters:
  run-test-a:
    type: boolean
    default: false
  run-test-b:
    type: boolean
    default: false
  run-test-c:
    type: boolean
    default: false
  environment:
    type: enum
    enum:
      - development
      - staging
    default: development

jobs:
  integration-test:
    docker:
      - image: cimg/base:stable
    resource_class: small
    parameters:
      environment:
        type: string
        default: development
      test-name:
        type: string
        default: ""
    steps:
      - run:
          name: Mock integration test << parameters.test-name >> on << parameters.environment >>
          command: |
            echo "Running integration test << parameters.test-name >> on << parameters.environment >>"
workflows:
  test-a:
    when: << pipeline.parameters.run-test-a >>
    jobs:
      - integration-test:
          environment: << pipeline.parameters.environment >>
          test-name: a
  test-b:
    when: << pipeline.parameters.run-test-b >>
    jobs:
      - integration-test:
          environment: << pipeline.parameters.environment >>
          test-name: b
  test-c:
    when: << pipeline.parameters.run-test-c >>
    jobs:
      - integration-test:
          environment: << pipeline.parameters.environment >>
          test-name: c
